### ISSUE TITLE
ValueError: buffer size must be a multiple of element size

### ISSUE THREAD

**Issue by dangerrockstar** [anmspro/Traffic-Signal-Violation-Detection-System#2]
hi there, 
i was trying to run your codes but i got this,
please have look the error

`python Project-GUI.py
Using TensorFlow backend.
2020-01-03 17:36:05.523745: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "Project-GUI.py", line 4, in <module>
    import object_detection as od
  File "E:\Traffic-Signal-Violation-Detection-System-master\Traffic-Signal-Violation-Detection-System-master\object_detection.py", line 411, in <module>
    weight_reader = WeightReader(weights_path)
  File "E:\Traffic-Signal-Violation-Detection-System-master\Traffic-Signal-Violation-Detection-System-master\object_detection.py", line 10, in __init__
    with open(weight_file, 'rb') as w_f:
FileNotFoundError: [Errno 2] No such file or directory: 'G:/Traffic Violation Detection/yolov3.weights'`

**Comment by dangerrockstar** [comment]
if fixed all path now but now i get something like this 
`Traceback (most recent call last):
  File "Project-GUI.py", line 4, in <module>
    import object_detection as od
  File "E:\Traffic-Signal-Violation-Detection-System-master\object_detection.py", line 411, in <module>
    weight_reader = WeightReader(weights_path)
  File "E:\Traffic-Signal-Violation-Detection-System-master\object_detection.py", line 25, in __init__
    self.all_weights = np.frombuffer(binary, dtype='float32')
ValueError: buffer size must be a multiple of element size`

**Comment by anmspro** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: 'G:/Traffic Violation Detection/yolov3.weights'`

Change the directory address.

**Comment by Esaanjum** [comment]
> 

Make sure you have downloaded the yolov3.weights file(237MB) from the link given in yolov3.txt file. This error can be caused by incorrect formatting/bad input of weights
