### ISSUE TITLE
mp文件打不开

### ISSUE THREAD

**Issue by fsasseil** [anmspro/Traffic-Signal-Violation-Detection-System#20]

**Comment by fsasseil** [comment]
[ WARN:0@10.814] global loadsave.cpp:241 cv::findDecoder imread_('E:\学习\数图实验\Traffic-Signal-Violation-Detection-System-master\Traffic-Signal-Violation-Detection-System-master\Resources\input\input.mp4'): can't open/read file: check file path/integrity
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\DELL\.conda\envs\d2l\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\Traffic-Signal-Violation-Detection-System-master\Traffic-Signal-Violation-Detection-System-master\Project-GUI.py", line 48, in open_file
    reader = imageio.get_reader(self.filename)
  File "C:\Users\DELL\.conda\envs\d2l\lib\site-packages\imageio\v2.py", line 290, in get_reader
    image_file = imopen(uri, "r" + mode, **imopen_args)
  File "C:\Users\DELL\.conda\envs\d2l\lib\site-packages\imageio\core\imopen.py", line 281, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `E:/Traffic-Signal-Violation-Detection-System-master/Traffic-Signal-Violation-Detection-System-master/Resources/input/input.mp4`` with iomode `r?`.
Based on the extension, the following plugins might add capable backends:
  FFMPEG:  pip install imageio[ffmpeg]
  pyav:  pip install imageio[pyav]

**Comment by fsasseil** [comment]
[ WARN:0@10.814] global loadsave.cpp:241 cv::findDecoder imread_('E:\\Traffic-Signal-Violation-Detection-System-master\Traffic-Signal-Violation-Detection-System-master\Resources\input\input.mp4'): can't open/read file: check file path/integrity
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\DELL\.conda\envs\d2l\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\\Traffic-Signal-Violation-Detection-System-master\Traffic-Signal-Violation-Detection-System-master\Project-GUI.py", line 48, in open_file
    reader = imageio.get_reader(self.filename)
  File "C:\Users\DELL\.conda\envs\d2l\lib\site-packages\imageio\v2.py", line 290, in get_reader
    image_file = imopen(uri, "r" + mode, **imopen_args)
  File "C:\Users\DELL\.conda\envs\d2l\lib\site-packages\imageio\core\imopen.py", line 281, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `E:/Traffic-Signal-Violation-Detection-System-master/Traffic-Signal-Violation-Detection-System-master/Resources/input/input.mp4`` with iomode `r?`.
Based on the extension, the following plugins might add capable backends:
  FFMPEG:  pip install imageio[ffmpeg]
  pyav:  pip install imageio[pyav]
