### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by mrmezan06** [anmspro/Traffic-Signal-Violation-Detection-System#4]
When I Open a video through file option, it's given this kind of error:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-1-3ebedd6a9bbf>", line 53, in open_file
    self.show_image('G:/Traffic Violation Detection/Traffic Signal Violation Detection System/Images/preview.jpg')
  File "<ipython-input-1-3ebedd6a9bbf>", line 57, in show_image
    self.imgSize = Image.open(frame)
  File "D:\Anaconda3\lib\site-packages\PIL\Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'G:/Traffic Violation Detection/Traffic Signal Violation Detection System/Images/preview.jpg'
Traceback (most recent call last):

  File "<ipython-input-1-3ebedd6a9bbf>", line 245, in <module>
    root.mainloop()

  File "D:\Anaconda3\lib\tkinter\__init__.py", line 1283, in mainloop
    self.tk.mainloop(n)

**Comment by anmspro** [comment]
The problem is in the directory address. 
 'G:/Traffic Violation Detection/Traffic Signal Violation Detection System/Images/preview.jpg'
Change the address according to the location in your pc.

**Comment by mrmezan06** [comment]
Yeah, I was fixed it.Forget to close the issue.
