### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_weights'

### ISSUE THREAD

**Issue by dongle329** [anmspro/Traffic-Signal-Violation-Detection-System#8]
Hello, when I run the following error occurred

Traceback (most recent call last):
  File "D:/traffic recognition/Traffic-Signal-Violation-Detection-System-master/Project-GUI.py", line 4, in <module>
    import object_detection as od
  File "D:\traffic recognition\Traffic-Signal-Violation-Detection-System-master\object_detection.py", line 412, in <module>
    weight_reader.load_weights(yolov3)
  File "D:\traffic recognition\Traffic-Signal-Violation-Detection-System-master\object_detection.py", line 40, in load_weights
    size = np.prod(norm_layer.get_weights()[0].shape)
AttributeError: 'NoneType' object has no attribute 'get_weights'

 
May I ask what this is about

**Comment by anmspro** [comment]
Faced similar issue while I was working due to a version mismatch. I hope this [thread](https://stackoverflow.com/questions/58963553/attributeerror-module-tensorflow-python-keras-backend-has-no-attribute-get-g) in stackoverflow helps.
